FROM golang:1.23-alpine AS builder

WORKDIR /build
COPY . .
RUN go mod download
RUN go build -o ./out ./cmd/consumer/consumer.go

FROM gcr.io/distroless/base-debian12
WORKDIR /app
COPY --from=builder /build/out .
CMD ["/app/out"]